sudo: required
dist: trusty
language: cpp
compiler: gcc
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - kalakris-cmake
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
    - cmake
before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes --remove ppa:kalakris-cmake/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
install: true
script: mkdir build && cd build && cmake ../ && make -r -j 2
